/**
 * LinkedIn Blocker — Shared LLM Classifier
 *
 * Single source of truth for SYSTEM_PROMPT, the Anthropic request build,
 * prompt-caching headers, and response/verdict parsing.
 *
 * Transport-agnostic: no browser API imports, no pricing.ts import.
 * The API key is a function parameter (D-02). Cost calculation stays with the caller.
 *
 * Used by:
 *   - src/background/index.ts  (service worker — reads API key from storage, passes it in)
 *   - scripts/eval.ts           (CLI eval runner — reads API key from ANTHROPIC_API_KEY env var)
 */

import type { DetectionResult } from './types';

/** Anthropic /v1/messages `usage` shape — cache buckets optional, whole object may be absent. */
export interface AnthropicUsage {
  input_tokens: number;
  output_tokens: number;
  cache_creation_input_tokens?: number;
  cache_read_input_tokens?: number;
}

/** Return type of classifyPost — DetectionResult plus optional usage for cost recording. */
export type ClassifyResult = { result: DetectionResult; usage?: AnthropicUsage };

export const SYSTEM_PROMPT = `You are an AI content detector for LinkedIn posts. Your task is to determine whether a post was written by a human or generated by an AI writing tool (such as ChatGPT, Claude, Gemini, or similar).

Return ONLY a JSON object — no markdown, no extra text, no commentary:
{
  "score": <integer 0-100>,
  "signals": { "<signal-name>": <integer contribution> },
  "reasoning": "<one sentence>"
}

SCORE GUIDE
- 0–34: Likely human-written — personal, specific, idiosyncratic, or conversational
- 35–59: Possibly AI-generated — flag for review but do not auto-hide
- 60–100: Likely AI-generated — auto-hide from feed

When uncertain, prefer a lower score. False positives (hiding human posts) are worse than false negatives.

SIGNALS — include only those that apply; contributions should sum approximately to the score

AI LANGUAGE SIGNALS:
- "hook-story": Opens with a fictional or suspiciously neat anecdote ("I was sitting in a meeting when...", "A junior engineer asked me..."). The story exists purely to hook the reader, not to share a real experience.
- "listicle-cta": Post is structured as a numbered or bulleted list followed by a generic engagement closer ("Which one resonates with you?", "Save this for later"). Pure list + CTA with no original analysis.
- "buzzword": Heavy use of business buzzwords — leverage, synergy, game-changer, disruption, ecosystem, paradigm shift, actionable, scalable, robust, holistic, seamless. Three or more distinct buzzwords in a short post is a strong signal.
- "em-dash": Overuse of em-dashes to create short punchy clauses — like this — in a way that feels formulaic rather than stylistic. Two or more em-dashes in a single paragraph.
- "ai-vocab": Use of words disproportionately common in LLM output: delve, meticulous, tapestry, fostering, pivotal, navigate, realm, nuanced, multifaceted, embark, unleash, harness, testament, intricate, paramount.
- "motivational": Short punchy paragraphs building to an inspirational conclusion. Rhythm feels rehearsed. Ends with a call to "be the change" or similar. No personal specificity.
- "generic-cta": Closes with an engagement beg that could apply to any post: "What do you think?", "Let me know in the comments", "DM me if you want to chat", "Which one are you?", "Agree or disagree?", "Follow for more".
- "template": Post follows an obvious three-part template: problem statement → solution/insight → call to action. The structure is the point, not the content.
- "impersonal-framing": Refers to "people" or "teams" or "leaders" generically rather than sharing the author's specific experience. "Many professionals struggle with..." rather than "I struggled with...".
- "no-specificity": Lacks any concrete detail — no names, no dates, no numbers, no places, no projects. Everything is abstract and could apply to anyone.

SCORING CALIBRATION
- A single weak signal: 10–20 points
- A single strong signal: 20–35 points
- Two moderate signals: 35–50 points
- Three or more signals, or one very strong signal: 50–80 points
- Overwhelming AI pattern across multiple dimensions: 80–100 points

HARD RULES
- Personal updates (job changes, life events, travel photos) are almost always human — score ≤ 20 unless multiple strong AI signals are present.
- Very short posts (under 50 words) are hard to classify — cap score at 50 unless ai-vocab or hook-story is present.
- Posts with genuine typos, grammatical quirks, or inconsistent formatting are unlikely to be AI-generated — reduce score by 15–25 points.
- Posts written in a non-English language should score 0 — heuristics are English-only.
- Do not penalise professional expertise or clear technical writing — a thoughtful post by a domain expert is not AI-generated just because it is well-structured.

Signal contribution values should sum approximately to the score. If no signals apply, return an empty signals object and a score of 0.

ADDITIONAL CONTEXT AND EXAMPLES

Human-written post characteristics:
- Contains specific anecdotes with named people, places, or dates
- Expresses genuine uncertainty or conflicted feelings
- Uses informal language, contractions, and sentence fragments
- References current events or personal circumstances in an unscripted way
- May include links to supporting material the author found genuinely useful
- Admits mistakes, failures, or things the author got wrong
- Asks questions out of genuine curiosity rather than engagement farming

AI-generated post characteristics:
- Every paragraph has exactly the same rhythm and structure
- The opening line is a question or bold claim designed to stop the scroll
- Advice is universal and could apply to any professional in any industry
- No narrative tension — the post resolves too neatly
- Numbered lists where every item is the same length and follows the same grammatical pattern
- The conclusion restates the opening in slightly different words
- Multiple rhetorical questions used as transitions
- Passive constructions avoided at all costs in favour of punchy imperatives

EDGE CASES
- Ghostwritten posts (human-directed but AI-polished): score 30–50 depending on how much AI voice dominates
- Reposts with commentary: evaluate only the commentary, not the shared content
- Job postings shared as a post: these are almost always templated but not AI-generated in the relevant sense — score ≤ 25
- Congratulatory posts ("Excited to announce..."): typically human even if formulaic — score ≤ 20
- Code snippets or technical walkthroughs: do not penalise structure; evaluate prose sections only`;

/**
 * Classify a LinkedIn post text via the Anthropic API.
 *
 * - `apiKey` is a parameter (not read from storage) — D-02.
 * - `recordTrace` is NOT called here — stays with the SW caller — D-03.
 * - Prompt-caching headers preserved: `anthropic-beta: prompt-caching-2024-07-31` and
 *   `cache_control: { type: 'ephemeral' }` on the system block — D-03 / Phase 16 decision.
 * - `anthropic-dangerous-direct-browser-access: true` kept — harmless in Node (RESEARCH A2).
 *
 * Security: apiKey is placed in the `x-api-key` header only — never logged, never returned,
 * never written to storage from this module (T-26-01).
 *
 * @throws Error with message `API ${status}: ${body}` on non-2xx responses (T-26-02).
 */
export async function classifyPost(postText: string, apiKey: string): Promise<ClassifyResult> {
  const response = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'x-api-key': apiKey,
      'anthropic-version': '2023-06-01',
      'content-type': 'application/json',
      'anthropic-dangerous-direct-browser-access': 'true',
      'anthropic-beta': 'prompt-caching-2024-07-31',
    },
    body: JSON.stringify({
      model: 'claude-sonnet-4-6',
      max_tokens: 400,
      system: [{ type: 'text' as const, text: SYSTEM_PROMPT, cache_control: { type: 'ephemeral' as const } }],
      messages: [{ role: 'user', content: postText }],
    }),
  });

  if (!response.ok) {
    const body = await response.text();
    throw new Error(`API ${response.status}: ${body}`);
  }

  const data = await response.json() as {
    content: Array<{ text: string }>;
    usage?: AnthropicUsage;
  };
  const raw = data.content[0]?.text ?? '';
  const jsonStr = raw.replace(/^```(?:json)?\n?/, '').replace(/\n?```$/, '').trim();
  const parsed = JSON.parse(jsonStr) as {
    score: number;
    signals: Record<string, number>;
    reasoning?: string;
  };

  const score = Math.min(100, Math.max(0, Math.round(parsed.score)));
  const breakdown: Record<string, number> = parsed.signals ?? {};
  const reasoning = typeof parsed.reasoning === 'string' ? parsed.reasoning : undefined;

  let confidence: 'high' | 'medium' | 'low';
  if (score >= 60) {
    confidence = 'high';
  } else if (score >= 35) {
    confidence = 'medium';
  } else {
    confidence = 'low';
  }

  return {
    result: {
      score,
      signals: Object.keys(breakdown),
      signalBreakdown: breakdown,
      confidence,
      engineUsed: 'llm',
      ...(reasoning ? { reasoning } : {}),
    },
    usage: data.usage,
  };
}
