// src/shared/generated-tool-registry.ts
// ============================================================
// DO NOT EDIT — generated by scripts/generate-skill-registry.ts
// Regenerate: npm run generate-skill-registry
// Stale-check: npm run check-tool-registry
// ============================================================

import type { Tool } from './skills/types';

import { domSelectorRederiveTool } from '../tools/library/dom-selector-rederive/dom-selector-rederive.tool';

export const GENERATED_TOOLS: readonly Tool<unknown, unknown>[] = [
  domSelectorRederiveTool,
];

export const GENERATED_TOOL_METADATA = {
  'dom-selector-rederive': { name: 'dom-selector-rederive', description: 'LLM tool that proposes CSS post-card selectors from a PII-stripped DOM skeleton. Calls the Anthropic API (via fetch in the service worker context) and returns ranked candidates with schema validation. Part of the Phase 23 self-healing selector pipeline.', kind: 'tool' as const },
} as const;
