// src/content/generated-skill-registry.ts
// ============================================================
// DO NOT EDIT — generated by scripts/generate-skill-registry.ts
// Regenerate: npm run generate-skill-registry
// Stale-check: npm run check-skill-registry
// ============================================================

import type { SignalSkill, ExclusionSkill } from '../shared/skills/types';

// Exclusion skill imports (priority order — DO NOT reorder, exclusion parity depends on it D-06)
import { sponsoredExclusionSkill } from '../skills/library/sponsored/sponsored.skill';

// Order MUST match CODE_SIGNAL_SKILLS from Phase 30 — golden-score snapshot depends on it (D-06)
export const GENERATED_SIGNAL_SKILLS: readonly SignalSkill[] = [
];

// Order MUST match CODE_EXCLUSION_SKILLS from Phase 30 — exclusion parity depends on it (D-06)
export const GENERATED_EXCLUSION_SKILLS: readonly ExclusionSkill[] = [
  sponsoredExclusionSkill,
];

// Descriptive metadata from SKILL.md manifests.
// NOT consumed by the runtime registry — skill objects carry their own kind/id/etc.
// Available for documentation and future LLM skill-authoring tooling.
export const GENERATED_SKILL_METADATA = {
  'sponsored': { name: 'sponsored-exclusion', description: 'Excludes sponsored/promoted posts before any detection runs. Checks for the SPONSORED_MARKER selector resolved via SelectorRegistry. Must run first (priority 1) to short-circuit before other exclusion checks.', kind: 'exclusion' as const },
} as const;
